### ISSUE TITLE
Library is not installed via Cocoapod.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [crowdconnected/colocator-ios-swift-3.1#2] opened 2017-09-26 09:20 UTC
Hi,
There is issue regarding installation of this library via CocoaPod.

**Comment by ambujshukla-cdn** [comment] 2017-09-27 07:04
Hi, did anyone check this issue as why the Cocoapod is not working as Carthage is not working proper with this and always giving this issue:-
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /private/var/containers/Bundle/Application/26665606-5413-4163-8C55-D135CBFF9BC8/ClockenFlap Test.app/Frameworks/CCLocation.framework/CCLocation
  Reason: image not found

After adding in Embeded libraries also it is not working.

**Comment by ambujshukla-cdn** [comment] 2017-09-27 07:43
After doing pod repo update, it started to install the colocator via pod but giving this issue after installing 2-3 libraries :- [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: CocoaLumberjack, ReSwift, Result, SwiftProtobuf, and TrueTime.

**Comment by kernchen** [comment] 2017-10-02 06:37
@ambujshukla-cdn, hi, sorry for delay in replying. Haven't been actively monitoring this channel yet. Could you confirm that this is an issue for this particular repository, i.e., Swift 3.1? I've been getting reports that this has happened for the Swift 3.2 from the team. Just to double check.

I will run another test with the the 3.1 version in Carthage to see if there might be an issue re the above and see if I can spot an issue. Could you kindly confirm your XCode version? So far I was only aware of that being a Cocoapod issue.

Also "use_framworks!" in the Podfile should be enabled as per the warning message above. Did you try this in the meanwhile?

**Comment by kernchen** [comment] 2017-10-02 06:45
Just noticed issues were not enable for 3.2 repository, it is now enabled. So in case this is a 3.2, please let me know, and we'll move the issues over there. Thanks a lot.

**Comment by ambujshukla-cdn** [comment] 2017-10-03 07:30
Hi Kernchen.
This is the result I got when try to install 3.2 via CocoaPod:-
 pod install
Ignoring psych-2.0.5 because its extensions are not built.  Try: gem pristine psych --version 2.0.5
Analyzing dependencies
Downloading dependencies
Installing CCLocation-Swift-3.2 (1.9.9)
Installing CocoaLumberjack (3.2.1)
Installing ReSwift (4.0.0)
Installing Result (3.2.4)
Installing SocketRocket (0.4.2)
Installing SwiftProtobuf (0.9.905)
Installing TrueTime (4.1.4)
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: CocoaLumberjack, ReSwift, Result, SwiftProtobuf, and TrueTime

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform ios with version 8.0 on target Coloc because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by kernchen** [comment] 2017-10-03 08:09
It seems, it might not only be TrueTime that is causing an issue here. Could you please confirm your XCode version, so I could try to reproduce / fix. I do have an Objective C test project as well for testing the library so we could check it in there once I know your configuration.

Also could you send the complete content of your Podfile please. Then it will be easier to reproduce as well. I'll also check Carthage to see if there are any issues there.

**Comment by ambujshukla-cdn** [comment] 2017-10-03 09:43
I tried to install in both the Xcode 8.3.3 and Xcode9.0.
This is the Podfile content:-
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColocatorDempApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  	  pod 'CCLocation-Swift-3.2’
  # Pods for ColocatorDempApp

end

**Comment by kernchen** [comment] 2017-10-11 14:21
This seems to be resolved, so I am going to close this issue.

**Closed by kernchen** 2017-10-11 14:21 UTC
